name: Update Blocklist

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

# Эта настройка принудительно включает Node.js 24 и убирает предупреждение
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Python script
        run: python update_list.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add my_custom_blocklist.list
          git commit -m "Auto-update blocklist" || echo "No changes to commit"
          git push
